version: '3.8'

services:
  trading_bot:
    build: .
    restart: always
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
    command: python execution/scalping_strategy.py

